import { useState } from 'react'
import './App.css'

const pillars = [
  ['01', 'Ingredients', 'What is in the can and why it is there.'],
  ['02', 'Sourcing', 'Where ingredients come from when disclosure is appropriate.'],
  ['03', 'Testing', 'The quality checks behind every product decision.'],
]

function Can() {
  return <div className="can can-blue" aria-label="KOVA flagship energy can"><div className="can-gloss" /><span className="can-rim">KOVA</span><strong>KOVA</strong><span className="can-energy">ENERGY</span><span className="can-lightning">/</span><span className="can-zero">ZERO SUGAR</span><span className="can-bottom">330 ML · 11.2 FL OZ</span></div>
}

function App() {
  const [votes, setVotes] = useState({ citrus: 68, berry: 42, yuzu: 31 })
  const [subscribed, setSubscribed] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [legalPage, setLegalPage] = useState(null)
  const vote = (key) => setVotes((current) => ({ ...current, [key]: current[key] + 1 }))

  return <main>
    <header className="site-header"><a className="wordmark" href="#top" aria-label="KOVA Energy home"><span>K</span>OVA<span className="wordmark-dot">.</span></a><nav className={menuOpen ? 'nav-open' : ''}><a href="#why">Why KOVA</a><a href="#transparency">Transparency</a><a href="#lab">KOVA Lab</a><a href="#roadmap">Roadmap</a></nav><button className="header-cta" type="button" onClick={() => document.querySelector('#updates')?.scrollIntoView()}>Follow the build <span>↗</span></button><button className="menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? '×' : '☰'}</button></header>

    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">KOVA ENERGY / BUILDING IN PUBLIC</p><h1>Energy,<br /><em>with receipts.</em></h1><p className="hero-intro">KOVA is being built around a simple idea: make one excellent product, explain every decision, and earn trust one can at a time.</p><div className="hero-actions"><a className="button button-primary" href="#transparency">See the standard <span>↓</span></a><a className="text-link" href="#lab">Join KOVA Lab <span>↗</span></a></div><div className="hero-stats"><div><strong>01</strong><span>flagship product</span></div><div><strong>0g</strong><span>sugar target</span></div><div><strong>100%</strong><span>open process</span></div></div></div><div className="hero-product"><div className="burst">NO<br />SECRETS<br /><b>INSIDE</b></div><Can /></div><div className="hero-ticker"><span>QUALITY BEFORE SCALE</span><span>IDENTIFY · EXPLAIN · FIX · LEARN</span><span>QUALITY BEFORE SCALE</span></div></section>

    <section className="why-section" id="why"><div className="section-heading"><div><p className="eyebrow">THE KOVA DIFFERENCE / 01</p><h2>Not just<br /><em>another can.</em></h2></div><p className="section-note">A consumer brand designed to be understood.</p></div><div className="principles"><article><b>01</b><h3>No unnecessary junk</h3><p>Every ingredient has a reason. “Clean” means justified, disclosed, and professionally reviewed, not fear-based marketing.</p></article><article><b>02</b><h3>Science beats marketing</h3><p>Product claims should be supported by evidence and reviewed by qualified professionals before they reach a label.</p></article><article><b>03</b><h3>Listen, then improve</h3><p>Customer feedback matters. It informs the work while safety, science, and regulatory requirements stay non-negotiable.</p></article></div></section>

    <section className="transparency" id="transparency"><div className="transparency-copy"><p className="eyebrow">THE TRANSPARENCY PLATFORM / 02</p><h2>Scan the can.<br /><em>See the work.</em></h2><p>When KOVA launches, a batch code will connect each can to the information behind it: ingredients, sourcing, manufacturing, testing, and version changes.</p><a className="text-link" href="#roadmap">How it will work <span>↗</span></a></div><div className="transparency-panel"><div className="scan-mark">K<span>/</span>V</div><div><span className="status-dot" /> PLATFORM IN DEVELOPMENT</div><h3>Every product has a story.</h3><p>We are building the place where you can read it.</p><div className="panel-lines"><span /><span /><span /></div></div></section>

    <section className="lab-section" id="lab"><div className="section-heading"><div><p className="eyebrow">KOVA LAB / 03</p><h2>Help shape<br /><em>the first drop.</em></h2></div><p className="section-note">The audience is part of the development.</p></div><div className="lab-grid"><div className="lab-copy"><p>KOVA Lab is where product ideas become better decisions. Vote on flavor directions, packaging, and what we should investigate next.</p><button className="button button-dark" type="button" onClick={() => document.querySelector('#flavor-vote')?.scrollIntoView()}>Cast your vote <span>↓</span></button></div><div className="vote-card" id="flavor-vote"><div className="vote-card-head"><span>FLAVOR DIRECTION / 001</span><span>OPEN VOTE</span></div><h3>What should KOVA taste like?</h3>{[['citrus', 'Bright citrus'], ['berry', 'Electric berry'], ['yuzu', 'Yuzu + mineral']].map(([key, label]) => <button className="vote-row" type="button" key={key} onClick={() => vote(key)}><span>{label}</span><span className="vote-track"><i style={{ width: `${votes[key]}%` }} /></span><b>{votes[key]}%</b></button>)}<small>Votes are directional, not a substitute for product testing.</small></div></div></section>

    <section className="roadmap" id="roadmap"><div><p className="eyebrow">THE BUILD / 04</p><h2>Slow is a<br /><em>strategy.</em></h2></div><div className="roadmap-list"><div className="roadmap-active"><b>01</b><span><strong>Idea + research</strong><small>Current stage · learning before launching</small></span><i>NOW</i></div><div><b>02</b><span><strong>Professional development</strong><small>Food science, quality, regulatory, and legal review</small></span><i>NEXT</i></div><div><b>03</b><span><strong>Testing + small launch</strong><small>Measure whether people choose KOVA again</small></span><i>SOON</i></div></div></section>

    <section className="updates" id="updates"><p className="eyebrow">BUILD KOVA WITH US / 05</p><h2>Get the honest<br /><em>progress report.</em></h2><p>Research notes, Lab votes, packaging tests, and real updates. No fake launch countdown.</p><form name="kova-updates" method="POST" data-netlify="true" netlify-honeypot="bot-field" onSubmit={() => setSubscribed(true)}><input type="hidden" name="form-name" value="kova-updates" /><input type="hidden" name="bot-field" /><input type="email" name="email" required placeholder="you@email.com" aria-label="Email address" /><button className="button button-primary" type="submit">{subscribed ? 'You’re in ✓' : 'Follow the build ↗'}</button></form><small className="form-note">Free signup. No launch spam. Unsubscribe anytime.</small></section>
    <footer><a className="wordmark" href="#top"><span>K</span>OVA<span className="wordmark-dot">.</span></a><p>Energy with intention.</p><div className="footer-links"><button type="button" onClick={() => setLegalPage('privacy')}>Privacy</button><button type="button" onClick={() => setLegalPage('terms')}>Terms</button><span>© 2026 KOVA ENERGY</span></div></footer>
    {legalPage && <div className="legal-backdrop" role="presentation" onClick={() => setLegalPage(null)}><section className="legal-modal" role="dialog" aria-modal="true" aria-labelledby="legal-title" onClick={(event) => event.stopPropagation()}><button className="legal-close" type="button" onClick={() => setLegalPage(null)} aria-label="Close legal information">×</button><p className="eyebrow">KOVA / PRE-LAUNCH INFORMATION</p><h2 id="legal-title">{legalPage === 'privacy' ? 'Privacy policy.' : 'Terms of use.'}</h2>{legalPage === 'privacy' ? <><p>This prototype does not sell products, process payments, use advertising trackers, or create user accounts. When deployed through Netlify, the progress signup sends the submitted email address to KOVA’s Netlify Forms dashboard so the team can respond with project updates.</p><p>Only submit an address you are authorized to share. KOVA should configure retention, access, notification, unsubscribe, and deletion procedures in Netlify before collecting public signups. This prototype policy should be reviewed and replaced with final legal text before launch.</p></> : <><p>This website is a pre-launch concept for KOVA Energy. Product details, nutrition targets, timelines, votes, and availability shown here are exploratory and are not an offer to sell a beverage.</p><p>KOVA will publish final ingredient, labeling, safety, regulatory, and purchase terms before commercial launch. Do not rely on prototype copy as medical, nutrition, or purchasing advice.</p></>}<button className="button button-primary legal-action" type="button" onClick={() => setLegalPage(null)}>Close <span>×</span></button></section></div>}
  </main>
}

export default App
